### ISSUE TITLE
Email notification: no error message on failure

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#11]
There is no error reported if the system fails to send an email notification. It always says email send successfully (which is false).

**Comment by sventhiel** [comment]
You are right. I am going to add proper exception handling, soon. After that it should be possible to modify the "system message" appropriately.

**Comment by sventhiel** [comment]
We should add logging information and try/catch for exception handling.

**Comment by DavidBlaa** [comment]
@sventhiel Did you work on that?

**Comment by sventhiel** [comment]
After internal review, the actual issue is not something that we could fix on our side. So if the system sends the mail, the problem should be one of the following:
1. SMTP configuration is wrong/faulty.
2. SMTP configuration is correct, but the SMTP itself is not allowed to send mails.
3. The mail is delivered, but inside the SPAM.
4. ...even more possible scenarios...

At the end, there are even more reasons why the send fails. But the quintessence is, that we have no further control of the email and smtp after the function is called.
