### ISSUE TITLE
Server Error in Entity Permissions

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#147]
**To Reproduce**
1. Go to 'Entity Permissions'
2. Click on 'Dataset'

**Comment by DavidBlaa** [comment]
The issue is because there is a dataset that has the status checkout.
In this View the system need to load the title of a dataset and this is only possible when the metadata is loadable and this is only possible, when a dataset is checked out. 

![image](https://user-images.githubusercontent.com/19665289/44255601-f0e76480-a206-11e8-9419-227520d7f600.png)

**Comment by DavidBlaa** [comment]
works in r2.12 rc4
