### ISSUE TITLE
Name of a person (party type) switches after edit

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#1484]
If a person edits their own account/profle and changes the first name, the name (first name + last name) of the party is shown in the wrong order (last name + first name).

How it looks on the Edit party page:
![grafik](https://github.com/BEXIS2/Core/assets/26480843/2854fb70-1639-4155-b7d1-58858ff9cd78)

How it looks (wrongly) on the Manage party page:
![grafik](https://github.com/BEXIS2/Core/assets/26480843/419dfb5d-8893-4ba8-b803-86bfaee3c1fb)

### How is it supposed to work?

On the party page the name should also stay in the right order: first name + last name

### How can it be reproduced?

Change the first name of an account with the edit option of the profile, so change the first name of your logged-in profile. Not with the admin function of someone else account.

**Comment by sventhiel** [comment]
There is a similar issue in other systems, e.g. AquaDiva. There is no solution for it at the moment, but it highly depends on wrong mappings.

**Comment by sventhiel** [comment]
After testing out on dev.bexis2.uni-jena.de, I wasn't able to reproduce the issue. So...,

1. even though other instances have issues with usernames as well, that particular one is occurring only at your instance
2. some specific configurations lead to that issue, that are not set/existing on dev.bexis2.uni-jena. So further investigation is necessary.
3. the issue is not existing anymore (which is unlikely, because nobody worked on it).

And probably, there are more reasons...
