### ISSUE TITLE
Sync should be performed after dataset creation (metadata only)

### ISSUE THREAD

**Issue by romangerlach** [BEXIS2/Core#174]
I created a tabular dataset (Create Dataset), but did not upload any data. When looking at the primary data view I get the following warning. 

![grafik](https://user-images.githubusercontent.com/16701900/45344803-e2d9f900-b5a4-11e8-86e4-450bdff8942d.png)

After doing the sync in Dataset Management I get the right view. 

![grafik](https://user-images.githubusercontent.com/16701900/45345319-56303a80-b5a6-11e8-87f9-9a25355a2e40.png)

solution: the sync should be performed after metadata creation already and should not after data upload only

**Comment by javadch** [comment]
Sync happens after each commit and the first commit (usually) happens after metadata is submitted.
The matter is that after submitting the metadata and (syncing) there is still **no data** to be shown.

The message appears because @DavidBlaa has decided to show such a message! Maybe he should check if there is a primary data, the dataset is tabular, and not yet synced, then show this message.
