### ISSUE TITLE
The logo and favicon comes not from tenant folder

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#205]
The files in the tenant are different from the logo and favicon which appear on the website. This issue is only with id=bexis. It works fine, when I change the id.

![tenant](https://user-images.githubusercontent.com/20185586/47635054-e83ed300-db53-11e8-8b19-711f59279123.png)

**Comment by sventhiel** [comment]
Hi @navabpourn,
Unfortunately, I don't get the problem. Obviously, there are mismatches between the names inside the tenant.xml and the actual images in the corresponding folder of the same tenant. If this is the case, you can either...

1. rename the images, or
2. change the names inside the tenant.xml.

Otherwise, please let me know what the actual issue is.

Best regards
Sven

**Comment by navabpourn** [comment]
Dear @sventhiel,

As I expected, the bexis folder in Workspace\Tenants should contain the files related to the bexis. But you see, the icons are different.
- Please open Site\web.config. This line is defined there: <add key="TenantId" value="bexis" />
- Open Workspace\Tenants\bexis\manifest. Check the Logo, FavIcon and Resource id.
- Open Workspace\Tenants\bexis\images and see the different file names.
But from where come icons of BEXIS2 instance when I install it for the first time?
Check this path: Site\Content\Images.
Is there a philosophy behind this behavior? I would like just know if coming the BEXIS logo from outside of Tenants is a bug or it is expected. 

Kind regards,
Nafiseh

**Comment by navabpourn** [comment]
The BEXIS2 logo in the first installation comes with the branding. The "bexis" folder in the Tenant is connected to another project.
