### ISSUE TITLE
Update a dataset add extra information in empty cells

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#209]
**Describe the bug**
I have a table with information about people: First Name, Last Name, Project Id, Email, Institution.
Some information was missed in the first version and I updated it later. After updating, in each row that I changed information in one cell, the update process added "16" in empty cells in this row.
In addition, the row with the information about Luise Ohman is doubled.
I will send you the whole folder of dataset versions by email because it includes the private information.

**Comment by sventhiel** [comment]
Could you give some more info about the primary key(s) you selected?

**Comment by navabpourn** [comment]
I selected all primary keys.

**Comment by sventhiel** [comment]
Well, then it is at least easy to explain, why some records occour twice or more after the update procedure. So consider the following scenario:

_**First Update** (which could be seen as create of the dataset)_

First Name | Last Name | Var 1 | Var 2
-- | -- | -- | --
Luisa | Ohmann | |


_**Second Update**_

First Name | Last Name | Var 1 | Var 2
-- | -- | -- | --
Luisa | Ohmann | | value x

_**Result**_

First Name | Last Name | Var 1 | Var 2
-- | -- | -- | --
Luisa | Ohmann | |
Luisa | Ohmann | | value x

_**Reason**_
Because you marked all columns to be the primary key, the system considers the rows as different objects. Even though _**First Name**_ and _**Last Name**_ are the same, the rows differ in _**Var 2**_.

_**Solution**_
You need to define the primary key more precisely, or create the dataset again (and consider a better primary key as well).

**Comment by navabpourn** [comment]
Thank Sven. You are right. I'll try again.
But adding "16" in empty cells is still a problem.

**Comment by sventhiel** [comment]
Yes, this is another issue that we should investigate.

**Comment by navabpourn** [comment]
I close this conversation and describe another issue separately.
