### ISSUE TITLE
As a user I would like to see units in the downloaded excel file

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#218]
**Is your feature request related to a problem? Please describe.**
When I download the primary data in Excel format I see only the variable names as the header. Currently, I miss information about units. 
I would like to have the units of the variable in the second row. 
The data could be placed in the third row.

**Comment by sventhiel** [comment]
Hi @navabpourn,

You are right, inside the "usual" xlsx files, there are no further information about the units related to a variable. But instead of the "usual" xlsx, you can download the dataset as a excel template (xlsm). Within that template, you get more detailed information about each variable, e.g. name, id, unit,  classification and data type. So a simple solution for this issue would be to download a dataset as excel template.

Best regards
Sven

**Comment by navabpourn** [comment]
Dear @sventhiel,

I agree with you, but data is not just a filled table, but also data information, in this case, units and data types. If units are missing in a data table, a part of the data is missed.
On the other hand, the header block in the Excel template is locked. The user can not change or copy information from this part.
My suggestion is to offer an xlsx format that contains all the information that exists in the excel template.

Cheers,
Nafiseh

**Comment by DavidBlaa** [comment]
#74

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
