### ISSUE TITLE
Are my data really secure?

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#221]
Hi everybody,

Recently I found a security issue, which is not the issue of BEXIS2, but the browser.
When I upload a dataset to the BEXIS2, all users with the Read right are able to see the data in the data table. The browser, in my case Chrome, makes the user able to copy data from the user interface and save.
Is there any way to avoid this behavior?  Could BEXIS2 offer an interface filling by images instead of characters? Or show only a part of data instead of the whole dataset?

I would be grateful if you pay your attention to this topic.

Nafiseh

**Comment by sventhiel** [comment]
Hi @navabpourn,

In the following, we are trying to answer all of your questions.

1.) Is there any way to avoid this behavior?
No. At least, not as far as we know.

2.) Could BEXIS2 offer an interface filling by images instead of characters?
Yes. In general, this is possible, but doesn't make any sense. Because even with an image, the user is able to copy/paste the data. Probably, the task is more cumbersome, but doesn't prevent the user from getting the data.

3.) Show only a part of data instead of the whole dataset?
Yes. In general, this is possible, but if the user has the right to see/get the data, this would be risky. Because the user is not aware of that additional "filtering". And even if the user knows it, what should he/she do with "parts" of the data?


Best regards
Sven

**Comment by navabpourn** [comment]
Thanks @sventhiel
