### ISSUE TITLE
Strange behavior of public only filter

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#299]
If not logged in i can´t browse not public datasets metadata. 
If logged in the public only is the default view wich gives a wrong impression to the user.

for our use case it is realy strange behavior.

**Comment by DavidBlaa** [comment]
basically the public search controller is public and should be visible without logging in if a menu entry is visible.

Public of course stands for public, which means that if a user is logged in or not, the user will see all freely available data sets. this can also be important for users who are logged in, because they don't need any further permissions.

**Comment by DavidBlaa** [comment]
- [ ] default -> search, not public search
- [ ] menu entry is search, not public search

**Comment by DavidBlaa** [comment]
both are configure able in the general.settings.xml

```xml
  <entry key="landingPage" value="ddm, PublicSearch, index" type="String" /> <!-- user is not logging in -> app goes to-->

  <entry key="landingPageForUsers" value="ddm, Home, index" type="String" /> <!-- landing page for users , when they logged in successfuly -->
```

**Comment by geofranzi** [comment]
works fine now
