### ISSUE TITLE
User Story 10: As a user I would like to be able to find and select an existing data structure when using the easy upload

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#43]
This feature is in addition to the capability to choose data attributes. Lacking this feature lead to have more (similar/identical) data structures.

- [ ] It should be possible to search for data structures. This search should allow for more than search by title only, and also should provide a preview of the variables of the data structures.
- [ ] The system can restrict the data structures based on a matching mechanism (optional)
- [ ] After a data structure is chosen, it should be used for validating, etc. of the dataset.

**Comment by MaSteinberg** [comment]
As discussed in a meeting on 05.06.2018, the task has been changed to:
If an existing datastructure matches the selection of the user during verification step (same variable names, same units and same datatypes, all in the same order), it should be reused for the new dataset instead of creating a new structure.

**Comment by geofranzi** [comment]
The easy upload will be deprecated in 2.15 and replaced by #824
