### ISSUE TITLE
logged off user can see non-public datasets

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#468]
BEXIS 2.13:
Click on the Search button shows all datasets even non-public ones. Someone who is not logged in could see also this list by clicking on the Search.

**Comment by DavidBlaa** [comment]
Hello Nafiseh, can you please explain again what the problem is?

Currently, it is implemented in a way that unlogged users only have access to the public search.
If you also want to have the normal search public, you have to do the following.

a) Set the search feature to public
b) enter the search function in the general.setting.xml (in the workspace) instead of the public search. 

These changes are described in the change.md

**Comment by navabpourn** [comment]
Dear David,
I cannot find the change.md. Could you please send me the link?

Thx, 
Nafiseh

**Comment by DavidBlaa** [comment]
https://github.com/BEXIS2/Core/blob/2.13/Release%20Notes/changes.md

**Comment by navabpourn** [comment]
Thank you David.
I changed the Search Feature to non-public and now it works fine :)
