### ISSUE TITLE
Error when using special characters in password 

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#526]
An error is shown when using special characters in password.
When yot use charaters like < and > an error page will show up.

**To Reproduce**
 - go to register
 - use as Password e.g. <pw>

**Expected behavior**
 - get a porper message or the cahracters are usable

**Actual behavior**
 - not caught exeption

**Screenshots**
![image](https://user-images.githubusercontent.com/3024715/80097976-6d018600-856c-11ea-9104-161e64865afc.png)

**Desktop (please complete the following information):**
 - Windows 10 edu 1903
 - Google Chrome Version 81.0.4044.122
 - Bexis 2.13 (demo)

**Comment by DavidBlaa** [comment]
it doesn't really seem to be a problem with the special characters. tests with < > are done and don't throw any error in the different situations. 

funny thing is that the password <pw> and probably only the one with these chars will throw a error.

Have you tried other passwords with those special characters < & > that cause an error? 
if so, please specify here.

**Comment by sventhiel** [comment]
Hej,

oh, that this page occurs is not desired. But it seems, that the only thing we could do is to check for some of the special characters. Because as the error messages suggests:

> A potentially dangerous Request.Form value was detected from the client.

So, we are going to change it a bit:

1. Exclude some characters from available set within the password and check those already on client-side.
2. We just change the error message and/or redirect to another page.


Cheers
