### ISSUE TITLE
Data structure template: upload with template gives validation error

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#740]
I donwloaded a template for a dataset, put 2 line with values inside and wanted to upload it. The validation (in the validation step) gaves message that variable names in excel would not fit with names in data structure.

**Comment by sventhiel** [comment]
Hej,

unfortunately, by default I wasn't able to reproduce that error. Indeed, I tried some further actions based on assumptions that may have happen in your instance. So...,

1. Creation of a new data structure (two variables)
2. Download of *.xlsm template
3. Modification of variable names inside that data structure
4. Adding of data within excel template
5. Upload of filled Excel template

At the validation, the system reports an error
![image](https://user-images.githubusercontent.com/55701246/115356758-43e5f680-a1bc-11eb-8a6f-ce03d5a3550c.png)

I know, that this procedure is straightforward, but other than that, I wasn't able to reproduce it in another way. At least without any further information. So, are you able to "exclude" such actions like "modification of data structure again, BEFORE upload of data"? Did the error message looked same/similar in your case? Because in may case, it is not telling anything about the variable name (although the error message is definitely related to it). 

Best regards
Sven

**Comment by CFuerstenau** [comment]
Here my use case.

1. create a dataset based on an existing dataset
2. download of *xlsm template
3. Adding of data within excel template
4. Upload of filled Excel template

After validate I got this error message
![grafik](https://user-images.githubusercontent.com/45873895/116055410-f5819d80-a67c-11eb-87be-3c9f07cc971e.png)
