### ISSUE TITLE
 request access tab is not there on the dataset

### ISSUE THREAD

**Issue by deepti15** [BEXIS2/Core#787]
Hello Team
I have installed  Version 2.14.2 (new deploy) on  WINServer19.
The issue is that the request access tab is not there on the dataset.
Please see the screenshot.

So i know per documentation that this feature was activated since version 2.12

So please guide me with steps that how can i activate this feature.

Kind Regards
Deepti
![error](https://user-images.githubusercontent.com/8344550/124425549-02033000-dd69-11eb-8ca5-ffce4f29aa6e.JPG)

**Comment by DavidBlaa** [comment]
I wanted to write you last week, unfortunately I forgot, sorry.

In order to send a request, it is necessary to know who the owner is.
In the metadata usually an owner is defined, which must be mapped with a user in the system.Metadaten wird meistens ein Owner festgelegt, der mit einen Nutzer im System gemappt werden muss.


When a person is then selected by the system, the system has 
the information, to which email the request can be sent and only then 
then the button becomes active.

Here are 2 HowTos that may help you.

https://github.com/BEXIS2/Core/wiki/How-to-prepare-to-delegate-the-responsibility-of-a-dataset-during-metadata-creation

https://github.com/BEXIS2/Core/wiki/How-to-setup-autocomplete-for-the-metadata-entries

We have recently released 2.14.4 and of course advise to use the new version.

https://github.com/BEXIS2/Core/releases/tag/2.14.4

if you get stuck, we can also meet in a video conference so that I can try to help you directly.

**Comment by DavidBlaa** [comment]
did the answers help?

**Comment by deepti15** [comment]
Thanks for the suggestion. we will install the new version 2.14.4 as you recommend and update you.

**Comment by shahab-ab** [comment]
We have already updated Bexis to its latest version. The quides were a bit complex at first glance such that we couldn't proceed with them to solve our issue.
It would be highly appreciated if we could meet in VC for a direct help.
Best regards
