### ISSUE TITLE
Fixed reference to workspace in web.config

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#796]
Fixed reference to workspace in web.config in line 16. If you move the workspace this breaks the application.

Suggestion: To make it easier to config BEXIS 2 an smaller confi file only with the needed parameters would be nice. 
![image](https://github.com/BEXIS2/Core/assets/19665289/e4c944bf-31d5-494f-afca-57952670ec60)

- [x] add credentials to the shell settings
- [ ] remove link from web.config

**Comment by DavidBlaa** [comment]
Can you please explain again when the problem occurs?
We have to regularly adjust the workspace in the published versions. So far, the problem has not occurred.

Is the problem perhaps occurring during development?
In that case, the projects put files into the workspace during the build process. We need to check whether the location of the workspace can come from the Web.config.

we also thought about extending the settings files, because most of the parameters we set in the web.config can be changed on the fly and a change in the web.config == restart of the page.

**Comment by MaJoHo** [comment]
<appSettings file="../Workspace/General/Configurations/Credentials.config">

This line just works if the workspace is next to site folder. But if i put the Workspace outside the intpub folder (what is highly recommendet for security reasons) the application dosen't work even when i adopt the WorkspacePath in line 42. So i have to change the Workspace path on to positions wich is confusing and unnessesary and corsed in my case a lot of frustration.

**Comment by MaJoHo** [comment]
lost again a lot of time with debugging because of the static path in the web.config than i remembered this issue.

**Comment by DavidBlaa** [comment]
add to generel settings - future david, thx

**Comment by sventhiel** [comment]
I am going to add it to the settings. Also to check proper handling of changing them on the fly.

**Comment by sventhiel** [comment]
As soon as the branch is merged back into dev, we can get rid of the credentials reference within web.config. At least for SMTP settings. We need to move the LDAP settings to General.Settings.json as well. 

Afterwards, the AppSettings reference to Credentials.json can be removed. BUT the reference "WorkspacePath" need to stay.

**Comment by DavidBlaa** [comment]
![Image](https://github.com/BEXIS2/Core/assets/19665289/259bff7b-ce8f-455b-81e9-cad075ac9302)

smtp in there but with false content
